# Generated by Django 4.1.4 on 2022-12-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
